---
title: 🧊异常
date: 2022-07-26 23:38:00
permalink: /pages/dc9bfe/
---

通常在LiteFlow组件里如果往外抛出异常，流程会中断。除了在[并行编排](/pages/b3446a/)中设置`ignoreError`关键字以外。

往外抛出的异常会被最外层的执行器捕获，并被包装进`LiteflowResponse`对象中。

你可以在`LiteflowResponse`对象中通过以下方法来获取异常

```java
LiteflowResponse response = flowExecutor.execute2Resp("chain1", 初始参数, CustomContext.class);
if (!response.isSuccess()){
  Exception e = response.getCause();
}
```

如果你的业务中有获取异常Code的需求，则你自定义的异常需要实现LiteFlow提供的`LiteFlowException`接口：

```java
public class YourException extends LiteFlowException {
	public YourException(String code, String message) {
		super(code, message);
	}
}
```

如果你的业务抛出了实现了`LiteFlowException`接口的异常，你则可以在`LiteflowResponse`中获得message和code信息：

```java
LiteflowResponse response = flowExecutor.execute2Resp("chain1", 初始参数, CustomContext.class);
if (!response.isSuccess()){
  Exception e = response.getCause();
  String code = response.getCode();
  String message = response.getMessage();
}
```

:::tip
如果你的异常没实现`LiteFlowException`，code和message字段都为null。
:::